FROM elixir:1.9

RUN apt-get update

RUN RUN apt-get install --yes build-essential inotify-tools postgresql-client

RUN mix local.hex --force && mix local.rebar --force

WORKDIR /app

ENV MIX_ENV=prod REPLACE_OS_VARS=true

COPY mix.exs mix.lock ./
RUN mix deps.get
COPY config ./config
RUN mix deps.compile
COPY . .
RUN mix phx.digest
RUN mix release --env=prod

ENTRYPOINT ["_build/prod/rel/bank_api/bin/bank_api"]
